In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_excel("SuperStore Sales DataSet.xlsx")
df.head()

,Row ID+O6G3A1:R6,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode,ind1,ind2
0,4918,CA-2019-160304,2019-01-01,2019-01-07,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",73.94,1,28.2668,NaN,Online,NaN,NaN
1,4919,CA-2019-160304,2019-01-02,2019-01-07,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",173.94,3,38.2668,NaN,Online,NaN,NaN
2,4920,CA-2019-160304,2019-01-02,2019-01-07,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Technology,Phones,GE 30522EE2,231.98,2,67.2742,NaN,Cards,NaN,NaN
3,3074,CA-2019-125206,2019-01-03,2019-01-05,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,...,Office Supplies,Storage,Recycled Steel Personal File for Hanging File ...,114.46,2,28.6150,NaN,Online,NaN,NaN
4,8604,US-2019-116365,2019-01-03,2019-01-08,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,...,Technology,Accessories,Imation Clip USB flash drive - 8 GB,30.08,2,-5.2640,NaN,Online,NaN,NaN

Data Cleaning

In [3]:
df.columns

Index(['Row ID+O6G3A1:R6', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Profit', 'Returns', 'Payment Mode', 'ind1',
       'ind2'],
      dtype='object')

In [5]:
df.isnull().sum()

Row ID+O6G3A1:R6       0
Order ID               0
Order Date             0
Ship Date              0
Ship Mode              0
Customer ID            0
Customer Name          0
Segment                0
Country                0
City                   0
State                  0
Region                 0
Product ID             0
Category               0
Sub-Category           0
Product Name           0
Sales                  0
Quantity               0
Profit                 0
Returns             5614
Payment Mode           0
ind1                5901
ind2                5901
dtype: int64

In [6]:
data = df[['Order Date','Customer Name','Region','Category','Sales','Profit']]
data.head()

  Order Date      Customer Name   Region         Category   Sales   Profit
0 2019-01-01      Brendan Murry     East        Furniture   73.94  28.2668
1 2019-01-02      Brendan Murry     East        Furniture  173.94  38.2668
2 2019-01-02      Brendan Murry     East       Technology  231.98  67.2742
3 2019-01-03       Lena Radford     West  Office Supplies  114.46  28.6150
4 2019-01-03  Christine Abelman  Central       Technology   30.08  -5.2640

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5901 entries, 0 to 5900
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order Date     5901 non-null   datetime64[ns]
 1   Customer Name  5901 non-null   object
 2   Region         5901 non-null   object
 3   Category       5901 non-null   object
 4   Sales          5901 non-null   float64
 5   Profit         5901 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 276.7+ KB

In [8]:
data.isnull().sum()

Order Date       0
Customer Name    0
Region           0
Category         0
Sales            0
Profit           0
dtype: int64

In [9]:
data['Order Date']=pd.to_datetime(data['Order Date'])

C:\Users\pagad\AppData\Local\Temp\ipykernel_20644\3159320396.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Order Date']=pd.to_datetime(data['Order Date'])

In [10]:
data

,Order Date,Customer Name,Region,Category,Sales,Profit
0,2019-01-01,Brendan Murry,East,Furniture,73.940,28.2668
1,2019-01-02,Brendan Murry,East,Furniture,173.940,38.2668
2,2019-01-02,Brendan Murry,East,Technology,231.980,67.2742
3,2019-01-03,Lena Radford,West,Office Supplies,114.460,28.6150
4,2019-01-03,Christine Abelman,Central,Technology,30.080,-5.2640
...,...,...,...,...,...,...
5896,2020-12-30,Patrick O'Donnell,East,Furniture,213.136,12.1176
5897,2020-12-30,Erica Bern,West,Office Supplies,295.904,4.5188
5898,2020-12-30,Jill Matthias,West,Office Supplies,388.024,-0.6048
5899,2020-12-30,Patrick O'Donnell,East,Office Supplies,462.776,19.7910
5900,2020-12-31,Jill Matthias,West,Office Supplies,2975.510,-0.6048

In [11]:
#Create new date column
data['Month']=data['Order Date'].dt.month
data['year']=data['Order Date'].dt.year

C:\Users\pagad\AppData\Local\Temp\ipykernel_20644\3659713361.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Month']=data['Order Date'].dt.month
C:\Users\pagad\AppData\Local\Temp\ipykernel_20644\3659713361.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['year']=data['Order Date'].dt.year

In [12]:
#Save cleaned csv data
data.to_csv("cleaned_sales_data.csv", index=False)
print("saved cleaned data!")

saved cleaned data!